name: socks_socket
description: SOCKS version 5 sockets for Dart and Flutter, *eg.* ElectrumX and/or Fulcrum over Tor via socket(s).
version: 1.1.1
repository: https://github.com/cypherstack/socks_socket

environment:
  sdk: ^3.0.6

dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
